[package]
name = "elf2psx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lexopt = "0.3"
goblin = "0.7"
anyhow = "1"
byteorder = "1"
parse_int = "0.6"
